name: Deploy

on:
    push:
        branches:
            - main
env:
  PEM_KEY: "${{secrets.PEM_KEY}}"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                node-version: "20.11.1"
            - name: Install dependencies
              run: npm ci
            - name: Run build
              run: npm run build         
            - uses: actions/upload-artifact@v4
              with:
                name: dist
                path: dist/angular-ci-cd/browser  
    
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions/setup-node@v2
              with:
                node-version: "20.11.1"
            - name: Install dependencies
              run: npm ci
            - name: Lint
              run: npm run lint            
                
    deploy:
      runs-on: ubuntu-latest
      steps:
        - name: SSH
          run: echo "Llave pem $PEM_KEY"        

               

